# The URL the site will be built for
base_url    = "https://example.com"
description = "A Zola theme made with tailwindcss"
theme       = "blow"
title       = "Blow"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-dark.css" },
  { theme = "ayu-light", filename = "syntax-light.css" },
]

taxonomies = [
  { name = "tags", paginate_by = 5, feed = true },
  { name = "categories", paginate_by = 5, feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
adsense_link       = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"
enable_adsense     = true
enable_multilingue = true
enable_search      = true
enable_sidebar     = true

[extra.lang]
items = [
  { lang = "en", links = [
    { base_url = "/", name = "English" },
    { base_url = "/fr", name = "French" },
  ] },
]

[extra.navbar]
items = [
  { lang = "en", links = [
    { url = "/", name = "Home" },
    { url = "/categories", name = "Categories" },
    { url = "/tags", name = "Tags" },
  ] },
]
title = "Banana Studios"

[extra.sidebar]
items = [
  { lang = "en", links = [
    { url = "/markdown", name = "Markdown" },
    { url = "/blog", name = "Blog" },
  ] },
]

# Index page
[extra.index]
image     = "https://via.placeholder.com/200"
image_alt = "Placeholder text describing the index's image."
title     = "Jacob LeCoq"

[extra.default_author]
avatar     = "https://via.placeholder.com/200"
avatar_alt = "Placeholder text describing the default author's avatar."
name       = "John Doe"

[extra.social]
email    = "lecoqjacob@gmail.com"
github   = "https://github.com/lecoqjacob"
gitlab   = "https://gitlab.com/lecoqjacob"
linkedin = "https://www.linkedin.com/in/jacob-lecoq/"
twitter  = "https://twitter.com/jacob_lecoq"

[extra.favicon]
android_chrome_192 = "/icons/android-chrome-192x192.png"
android_chrome_512 = "/icons/android-chrome-512x512.png"
apple_touch_icon   = "/icons/apple-touch-icon.png"
favicon            = "/icons/favicon.ico"
favicon_16x16      = "/icons/favicon-16x16.png"
favicon_32x32      = "/icons/favicon-32x32.png"
manifest           = "/icons/site.webmanifest"
